name: Go

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/dependabot.yml'
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ main ]
env:
  BINARY: 'server'
  GO_VERSION: '1.17'
  
jobs:
  pre_flight:
    runs-on: ubuntu-latest
    
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog : ${{ steps.tag_version.outputs.changelog }}
    steps:
    - name: Establish tags and versions
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
  build:
    runs-on: ubuntu-latest
    needs: [pre_flight]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "^${{ env.GO_VERSION }}"
    - name: Setting Up protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.14.0'

    - name: Install protoc Plugins
      run:  |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
        go install github.com/fluffy-bunny/grpcdotnetgo/protoc-gen-go-di/cmd/protoc-gen-go-di
        
    - name: go mod vendor
      run: |
        go mod tidy -compat="1.17" 
        go mod download
        go mod vendor
    
    - name: make proto go
      run: |
        protoc --proto_path=. --proto_path=vendor --proto_path=vendor/github.com/fluffy-bunny  --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --go-di_out=. --go-di_opt=paths=source_relative ./internal/grpcContracts/helloworld/helloworld.proto
        
    - name: move vendor sub folders
      run: |
        mv ./vendor/github.com/fluffy-bunny/sarulabsdi/genny/ ./genny/sarulabsdi/
        rm -rf ./vendor/
        
    - name: Install Mockgen
      run: |
        go install github.com/golang/mock/mockgen@latest
    - name: Install genny
      run: |
        go version
        go install github.com/cheekybits/genny@latest
    
    - name: GO GENERATE
      run: |
        go generate -x ./...
        rm -rf ./genny/sarulabsdi/
        go mod tidy -compat="1.17" 
        
    # NOTE: This will NOT trigger another run of CI.yml
    - name: AutoCommit
      uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: Apply genny and mockgen changes
        
    # Test pkg for -race
    - name: Test 
      run: |
        go test -v  ./... -race 
        
    - name: Build
      run: go build -v ./...

 
